<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Desa_model extends CI_Model
{

    public $table = 'desa';
    public $id = 'id_desa';
    public $id_kecamatan = 'id_kecamatan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by kecamatan
    function get_by_kecamatan($id_kecamatan)
    {
        //$this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->where('desa.id_kecamatan', $id_kecamatan);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->like('id_desa', $q);
	$this->db->or_like('desa.id_kecamatan', $q);
	$this->db->or_like('desa.nama_desa', $q);
	$this->db->or_like('desa.col1', $q);
	$this->db->or_like('desa.col2', $q);
	$this->db->or_like('desa.col3', $q);
	$this->db->or_like('desa.col4', $q);
	$this->db->or_like('desa.col5', $q);
	$this->db->or_like('desa.created_at', $q);
	$this->db->or_like('desa.created_by', $q);
	$this->db->or_like('desa.updated_at', $q);
	$this->db->or_like('desa.updated_by', $q);
	$this->db->or_like('desa.isactive', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_desa', $q);
	$this->db->or_like('desa.id_kecamatan', $q);
	$this->db->or_like('desa.nama_desa', $q);
	$this->db->or_like('desa.col1', $q);
	$this->db->or_like('desa.col2', $q);
	$this->db->or_like('desa.col3', $q);
	$this->db->or_like('desa.col4', $q);
	$this->db->or_like('desa.col5', $q);
	$this->db->or_like('desa.created_at', $q);
	$this->db->or_like('desa.created_by', $q);
	$this->db->or_like('desa.updated_at', $q);
	$this->db->or_like('desa.updated_by', $q);
	$this->db->or_like('desa.isactive', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Desa_model.php */
/* Location: ./application/models/Desa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-17 23:51:55 */
/* http://harviacode.com */