<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pelapor_model extends CI_Model
{

    public $table = 'pelapor';
    public $id = 'id_pelapor';
    public $nik = 'nik_pelapor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('desa','desa.id_desa=pelapor.id_desa');
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->join('agama','agama.id_agama=pelapor.id_agama'); 
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('desa','desa.id_desa=pelapor.id_desa');
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->join('agama','agama.id_agama=pelapor.id_agama');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by nik
    function get_by_nik($nik_pelapor)
    {
        $this->db->join('desa','desa.id_desa=pelapor.id_desa');
        $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
        $this->db->join('agama','agama.id_agama=pelapor.id_agama');
        $this->db->where($this->nik, $nik_pelapor);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->join('desa','desa.id_desa=pelapor.id_desa');
    $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
    $this->db->join('agama','agama.id_agama=pelapor.id_agama');
    $this->db->like('id_pelapor', $q);
	$this->db->or_like('nama_pelapor', $q);
	$this->db->or_like('pelapor.id_agama', $q);
	$this->db->or_like('pelapor.id_desa', $q);
	$this->db->or_like('alamat_pelapor', $q);
	$this->db->or_like('no_hp_pelapor', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->join('desa','desa.id_desa=pelapor.id_desa');
    $this->db->join('kecamatan','kecamatan.id_kecamatan=desa.id_kecamatan');
    $this->db->join('agama','agama.id_agama=pelapor.id_agama');
    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_pelapor', $q);
	$this->db->or_like('nama_pelapor', $q);
	$this->db->or_like('pelapor.id_agama', $q);
	$this->db->or_like('pelapor.id_desa', $q);
	$this->db->or_like('alamat_pelapor', $q);
	$this->db->or_like('no_hp_pelapor', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pelapor_model.php */
/* Location: ./application/models/Pelapor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-19 08:14:42 */
/* http://harviacode.com */